/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadTextRouteImport } from './routes/upload-text'
import { Route as UploadJsonRouteImport } from './routes/upload-json'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateDeckRouteImport } from './routes/create-deck'
import { Route as IndexRouteImport } from './routes/index'

const UploadTextRoute = UploadTextRouteImport.update({
  id: '/upload-text',
  path: '/upload-text',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadJsonRoute = UploadJsonRouteImport.update({
  id: '/upload-json',
  path: '/upload-json',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateDeckRoute = CreateDeckRouteImport.update({
  id: '/create-deck',
  path: '/create-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-deck': typeof CreateDeckRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/study': typeof StudyRoute
  '/upload-json': typeof UploadJsonRoute
  '/upload-text': typeof UploadTextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-deck': typeof CreateDeckRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/study': typeof StudyRoute
  '/upload-json': typeof UploadJsonRoute
  '/upload-text': typeof UploadTextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-deck': typeof CreateDeckRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/study': typeof StudyRoute
  '/upload-json': typeof UploadJsonRoute
  '/upload-text': typeof UploadTextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-deck'
    | '/login'
    | '/practice'
    | '/search'
    | '/study'
    | '/upload-json'
    | '/upload-text'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-deck'
    | '/login'
    | '/practice'
    | '/search'
    | '/study'
    | '/upload-json'
    | '/upload-text'
  id:
    | '__root__'
    | '/'
    | '/create-deck'
    | '/login'
    | '/practice'
    | '/search'
    | '/study'
    | '/upload-json'
    | '/upload-text'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateDeckRoute: typeof CreateDeckRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  SearchRoute: typeof SearchRoute
  StudyRoute: typeof StudyRoute
  UploadJsonRoute: typeof UploadJsonRoute
  UploadTextRoute: typeof UploadTextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-text': {
      id: '/upload-text'
      path: '/upload-text'
      fullPath: '/upload-text'
      preLoaderRoute: typeof UploadTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-json': {
      id: '/upload-json'
      path: '/upload-json'
      fullPath: '/upload-json'
      preLoaderRoute: typeof UploadJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-deck': {
      id: '/create-deck'
      path: '/create-deck'
      fullPath: '/create-deck'
      preLoaderRoute: typeof CreateDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateDeckRoute: CreateDeckRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  SearchRoute: SearchRoute,
  StudyRoute: StudyRoute,
  UploadJsonRoute: UploadJsonRoute,
  UploadTextRoute: UploadTextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
